package ac.grim.grimac.manager;

import ac.grim.grimac.utils.data.VelocityData;
import ac.grim.grimac.utils.math.Vector3dm;
import org.jetbrains.annotations.Nullable;

/** Builds a mutable setback velocity without changing queued packet data. */
final class SetbackVelocity {
    private SetbackVelocity() {
    }

    static Vector3dm compose(Vector3dm previous, @Nullable VelocityData knockback,
                            @Nullable VelocityData explosion) {
        Vector3dm velocity = previous.clone();
        if (knockback != null && !knockback.isSetback) {
            velocity = knockback.vector.clone();
        }
        // A later velocity packet overrides the explosion. Preserve the existing
        // rule preventing reuse of a velocity generated by a previous setback.
        if (explosion != null && (knockback == null
                || (knockback.transaction < explosion.transaction && !knockback.isSetback))) {
            velocity.add(explosion.vector);
        }
        return velocity;
    }
}
